// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetHistoryRequest struct {
	RoleId int `path:"role_id"`
}

type GetHistoryResponse struct {
	Messages []Message `json:"messages"`
}

type GetRoleRequest struct {
	Id int `path:"id"`
}

type GetRoleResponse struct {
	Role Role `json:"role"`
}

type GetRolesRequest struct {
}

type GetRolesResponse struct {
	Roles []Role `json:"roles"`
}

type Message struct {
	Id        int    `json:"id"`
	RoleId    int    `json:"role_id"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
}

type Role struct {
	Id          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Personality string `json:"personality"`
}

type SendMessageRequest struct {
	RoleId  int    `json:"role_id"`
	Content string `json:"content"`
}

type SendMessageResponse struct {
	Message Message `json:"message"`
}
