// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"serve-go/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/messages",
				Handler: SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/messages/:role_id",
				Handler: GetHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: GetRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roles/set",
				Handler: SetRoleApiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id",
				Handler: GetRoleHandler(serverCtx),
			},
		},
	)
}
