// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: internal/grpc/role_play.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolePlayService_SetRole_FullMethodName           = "/roleplay.RolePlayService/SetRole"
	RolePlayService_ChatWithRole_FullMethodName      = "/roleplay.RolePlayService/ChatWithRole"
	RolePlayService_ResetConversation_FullMethodName = "/roleplay.RolePlayService/ResetConversation"
	RolePlayService_GetPresetRoles_FullMethodName    = "/roleplay.RolePlayService/GetPresetRoles"
)

// RolePlayServiceClient is the client API for RolePlayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 角色扮演服务
type RolePlayServiceClient interface {
	// 设置角色
	SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error)
	// 与角色对话
	ChatWithRole(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// 重置对话
	ResetConversation(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// 获取预设角色列表
	GetPresetRoles(ctx context.Context, in *GetPresetRolesRequest, opts ...grpc.CallOption) (*GetPresetRolesResponse, error)
}

type rolePlayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolePlayServiceClient(cc grpc.ClientConnInterface) RolePlayServiceClient {
	return &rolePlayServiceClient{cc}
}

func (c *rolePlayServiceClient) SetRole(ctx context.Context, in *SetRoleRequest, opts ...grpc.CallOption) (*SetRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleResponse)
	err := c.cc.Invoke(ctx, RolePlayService_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePlayServiceClient) ChatWithRole(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, RolePlayService_ChatWithRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePlayServiceClient) ResetConversation(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, RolePlayService_ResetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePlayServiceClient) GetPresetRoles(ctx context.Context, in *GetPresetRolesRequest, opts ...grpc.CallOption) (*GetPresetRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresetRolesResponse)
	err := c.cc.Invoke(ctx, RolePlayService_GetPresetRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolePlayServiceServer is the server API for RolePlayService service.
// All implementations must embed UnimplementedRolePlayServiceServer
// for forward compatibility.
//
// 角色扮演服务
type RolePlayServiceServer interface {
	// 设置角色
	SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error)
	// 与角色对话
	ChatWithRole(context.Context, *ChatRequest) (*ChatResponse, error)
	// 重置对话
	ResetConversation(context.Context, *ResetRequest) (*ResetResponse, error)
	// 获取预设角色列表
	GetPresetRoles(context.Context, *GetPresetRolesRequest) (*GetPresetRolesResponse, error)
	mustEmbedUnimplementedRolePlayServiceServer()
}

// UnimplementedRolePlayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolePlayServiceServer struct{}

func (UnimplementedRolePlayServiceServer) SetRole(context.Context, *SetRoleRequest) (*SetRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedRolePlayServiceServer) ChatWithRole(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatWithRole not implemented")
}
func (UnimplementedRolePlayServiceServer) ResetConversation(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetConversation not implemented")
}
func (UnimplementedRolePlayServiceServer) GetPresetRoles(context.Context, *GetPresetRolesRequest) (*GetPresetRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresetRoles not implemented")
}
func (UnimplementedRolePlayServiceServer) mustEmbedUnimplementedRolePlayServiceServer() {}
func (UnimplementedRolePlayServiceServer) testEmbeddedByValue()                         {}

// UnsafeRolePlayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolePlayServiceServer will
// result in compilation errors.
type UnsafeRolePlayServiceServer interface {
	mustEmbedUnimplementedRolePlayServiceServer()
}

func RegisterRolePlayServiceServer(s grpc.ServiceRegistrar, srv RolePlayServiceServer) {
	// If the following call panics, it indicates UnimplementedRolePlayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolePlayService_ServiceDesc, srv)
}

func _RolePlayService_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePlayServiceServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePlayService_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePlayServiceServer).SetRole(ctx, req.(*SetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePlayService_ChatWithRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePlayServiceServer).ChatWithRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePlayService_ChatWithRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePlayServiceServer).ChatWithRole(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePlayService_ResetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePlayServiceServer).ResetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePlayService_ResetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePlayServiceServer).ResetConversation(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePlayService_GetPresetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePlayServiceServer).GetPresetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePlayService_GetPresetRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePlayServiceServer).GetPresetRoles(ctx, req.(*GetPresetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolePlayService_ServiceDesc is the grpc.ServiceDesc for RolePlayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolePlayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "roleplay.RolePlayService",
	HandlerType: (*RolePlayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRole",
			Handler:    _RolePlayService_SetRole_Handler,
		},
		{
			MethodName: "ChatWithRole",
			Handler:    _RolePlayService_ChatWithRole_Handler,
		},
		{
			MethodName: "ResetConversation",
			Handler:    _RolePlayService_ResetConversation_Handler,
		},
		{
			MethodName: "GetPresetRoles",
			Handler:    _RolePlayService_GetPresetRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/role_play.proto",
}
