// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/grpc/role_play.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设置角色请求
type SetRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleName       string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CustomName     string                 `protobuf:"bytes,2,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	CustomPrompt   string                 `protobuf:"bytes,3,opt,name=custom_prompt,json=customPrompt,proto3" json:"custom_prompt,omitempty"`
	CustomGreeting string                 `protobuf:"bytes,4,opt,name=custom_greeting,json=customGreeting,proto3" json:"custom_greeting,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetRoleRequest) Reset() {
	*x = SetRoleRequest{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleRequest) ProtoMessage() {}

func (x *SetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleRequest.ProtoReflect.Descriptor instead.
func (*SetRoleRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{0}
}

func (x *SetRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *SetRoleRequest) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *SetRoleRequest) GetCustomPrompt() string {
	if x != nil {
		return x.CustomPrompt
	}
	return ""
}

func (x *SetRoleRequest) GetCustomGreeting() string {
	if x != nil {
		return x.CustomGreeting
	}
	return ""
}

// 设置角色响应
type SetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Greeting      string                 `protobuf:"bytes,3,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleResponse) Reset() {
	*x = SetRoleResponse{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleResponse) ProtoMessage() {}

func (x *SetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleResponse.ProtoReflect.Descriptor instead.
func (*SetRoleResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{1}
}

func (x *SetRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetRoleResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

// 对话请求
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 对话响应
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 重置请求
type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{4}
}

// 重置响应
type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{5}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取预设角色请求
type GetPresetRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresetRolesRequest) Reset() {
	*x = GetPresetRolesRequest{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresetRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresetRolesRequest) ProtoMessage() {}

func (x *GetPresetRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresetRolesRequest.ProtoReflect.Descriptor instead.
func (*GetPresetRolesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{6}
}

// 预设角色信息
type PresetRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Emoji         string                 `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetRole) Reset() {
	*x = PresetRole{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetRole) ProtoMessage() {}

func (x *PresetRole) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetRole.ProtoReflect.Descriptor instead.
func (*PresetRole) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{7}
}

func (x *PresetRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PresetRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PresetRole) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

// 获取预设角色响应
type GetPresetRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*PresetRole          `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresetRolesResponse) Reset() {
	*x = GetPresetRolesResponse{}
	mi := &file_internal_grpc_role_play_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresetRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresetRolesResponse) ProtoMessage() {}

func (x *GetPresetRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_role_play_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresetRolesResponse.ProtoReflect.Descriptor instead.
func (*GetPresetRolesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_role_play_proto_rawDescGZIP(), []int{8}
}

func (x *GetPresetRolesResponse) GetRoles() []*PresetRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_internal_grpc_role_play_proto protoreflect.FileDescriptor

const file_internal_grpc_role_play_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/grpc/role_play.proto\x12\broleplay\"\x9c\x01\n" +
	"\x0eSetRoleRequest\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x1f\n" +
	"\vcustom_name\x18\x02 \x01(\tR\n" +
	"customName\x12#\n" +
	"\rcustom_prompt\x18\x03 \x01(\tR\fcustomPrompt\x12'\n" +
	"\x0fcustom_greeting\x18\x04 \x01(\tR\x0ecustomGreeting\"a\n" +
	"\x0fSetRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bgreeting\x18\x03 \x01(\tR\bgreeting\"'\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Z\n" +
	"\fChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0e\n" +
	"\fResetRequest\"C\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15GetPresetRolesRequest\"X\n" +
	"\n" +
	"PresetRole\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\"D\n" +
	"\x16GetPresetRolesResponse\x12*\n" +
	"\x05roles\x18\x01 \x03(\v2\x14.roleplay.PresetRoleR\x05roles2\xab\x02\n" +
	"\x0fRolePlayService\x12>\n" +
	"\aSetRole\x12\x18.roleplay.SetRoleRequest\x1a\x19.roleplay.SetRoleResponse\x12=\n" +
	"\fChatWithRole\x12\x15.roleplay.ChatRequest\x1a\x16.roleplay.ChatResponse\x12D\n" +
	"\x11ResetConversation\x12\x16.roleplay.ResetRequest\x1a\x17.roleplay.ResetResponse\x12S\n" +
	"\x0eGetPresetRoles\x12\x1f.roleplay.GetPresetRolesRequest\x1a .roleplay.GetPresetRolesResponseB\x18Z\x16serve-go/internal/grpcb\x06proto3"

var (
	file_internal_grpc_role_play_proto_rawDescOnce sync.Once
	file_internal_grpc_role_play_proto_rawDescData []byte
)

func file_internal_grpc_role_play_proto_rawDescGZIP() []byte {
	file_internal_grpc_role_play_proto_rawDescOnce.Do(func() {
		file_internal_grpc_role_play_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_role_play_proto_rawDesc), len(file_internal_grpc_role_play_proto_rawDesc)))
	})
	return file_internal_grpc_role_play_proto_rawDescData
}

var file_internal_grpc_role_play_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_grpc_role_play_proto_goTypes = []any{
	(*SetRoleRequest)(nil),         // 0: roleplay.SetRoleRequest
	(*SetRoleResponse)(nil),        // 1: roleplay.SetRoleResponse
	(*ChatRequest)(nil),            // 2: roleplay.ChatRequest
	(*ChatResponse)(nil),           // 3: roleplay.ChatResponse
	(*ResetRequest)(nil),           // 4: roleplay.ResetRequest
	(*ResetResponse)(nil),          // 5: roleplay.ResetResponse
	(*GetPresetRolesRequest)(nil),  // 6: roleplay.GetPresetRolesRequest
	(*PresetRole)(nil),             // 7: roleplay.PresetRole
	(*GetPresetRolesResponse)(nil), // 8: roleplay.GetPresetRolesResponse
}
var file_internal_grpc_role_play_proto_depIdxs = []int32{
	7, // 0: roleplay.GetPresetRolesResponse.roles:type_name -> roleplay.PresetRole
	0, // 1: roleplay.RolePlayService.SetRole:input_type -> roleplay.SetRoleRequest
	2, // 2: roleplay.RolePlayService.ChatWithRole:input_type -> roleplay.ChatRequest
	4, // 3: roleplay.RolePlayService.ResetConversation:input_type -> roleplay.ResetRequest
	6, // 4: roleplay.RolePlayService.GetPresetRoles:input_type -> roleplay.GetPresetRolesRequest
	1, // 5: roleplay.RolePlayService.SetRole:output_type -> roleplay.SetRoleResponse
	3, // 6: roleplay.RolePlayService.ChatWithRole:output_type -> roleplay.ChatResponse
	5, // 7: roleplay.RolePlayService.ResetConversation:output_type -> roleplay.ResetResponse
	8, // 8: roleplay.RolePlayService.GetPresetRoles:output_type -> roleplay.GetPresetRolesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpc_role_play_proto_init() }
func file_internal_grpc_role_play_proto_init() {
	if File_internal_grpc_role_play_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_role_play_proto_rawDesc), len(file_internal_grpc_role_play_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_role_play_proto_goTypes,
		DependencyIndexes: file_internal_grpc_role_play_proto_depIdxs,
		MessageInfos:      file_internal_grpc_role_play_proto_msgTypes,
	}.Build()
	File_internal_grpc_role_play_proto = out.File
	file_internal_grpc_role_play_proto_goTypes = nil
	file_internal_grpc_role_play_proto_depIdxs = nil
}
